version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
      args:
        - docker_host_ip
    environment:
      - TPG_DB=notepad
      - TPG_USER=admin
      - TPG_PASS=admin
      - TPG_HOST=db
      - TPG_PORT=5431
    ports:
      - '8000:8000'

