FROM postgres:12.4-alpine as builder

WORKDIR /app

ARG docker_host_ip
ENV TPG_DB=notepad
ENV TPG_USER=admin
ENV TPG_PASS=admin
ENV TPG_HOST=$docker_host_ip
# ENV TPG_PORT=5431
ENV TPG_PORT=5432

RUN bash -c "export PGPASSWORD=$TPG_PASS; psql -h $TPG_HOST -p $TPG_PORT -U $TPG_USER -d $TPG_DB -c \"SELECT version();\" > output.txt"
# RUN bash -c "export PGPASSWORD=$TPG_PASS; psql -h $TPG_HOST -p $TPG_PORT -U $TPG_USER -d $TPG_DB -c \"SELECT version();\" > output.txt"

CMD ["cat", "output.txt"]