name: main_workflow
on: push

env:
  REGISTRY: ghcr.io

jobs:
  main-job:
    name: Build docker images
    runs-on: ubuntu-latest
    permissions:
      # TODO: ?
      contents: read
      # TODO: ?
      packages: write

    container: docker/compose

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Docker buildx
        run: |
          apk add curl jq
          export BUILDX_VERSION=$(curl -s 'https://api.github.com/repos/docker/buildx/releases' | jq -r '.[0].tag_name')
          curl -L --output /docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
          chmod a+x /docker-buildx
          mkdir -p /usr/lib/docker/cli-plugins
          cp /docker-buildx /usr/lib/docker/cli-plugins/docker-buildx

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/vladimirlogachev/registry-test
          # https://github.com/docker/metadata-action#tags-input
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}