name: main_workflow
on: push

jobs:
  main-job:
    name: Build docker images
    runs-on: ubuntu-latest

    container: docker/compose

    steps:
      - uses: actions/checkout@v2
      - name: Build and tag registry-test image
        run: |
          docker-compose build registry-test