name: main_workflow
on: push

jobs:
  main-job:
    name: Use cache
    runs-on: ubuntu-latest

    # container: docker/compose

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: cache
          key: cache-key
          restore-keys: cache-key

      - name: Use the file - read, append, read again
        run: |
          cat cache/sample.txt
          echo "\n---\n"
          echo "\nchanges...\n" >> cache/sample.txt
          echo "\n--- ---\n"
          cat cache/sample.txt