name: main_workflow
on: push

jobs:
  main-job:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Build backend in Docker
      #   run: |
      #     docker-compose pull
      #     docker-compose up -Vd db
      #     docker_host_ip=$(ip route show | awk '/default/ {print $3}') docker-compose build backend
      #     docker-compose up backend
      #     docker-compose down -v

      - name: Build backend in Docker
        run: |
          docker-compose pull
          docker-compose up -Vd db
          bash -c "export PGPASSWORD=admin; psql -h localhost -p 5431 -U admin -d notepad -c \"SELECT version();\" > output.txt"
          echo $(cat output.txt)
          docker-compose down -v