name: main_workflow
on: push

jobs:
  main-job:
    name: Build docker images
    runs-on: ubuntu-latest
    container: postgres:12-alpine

    services:
      db:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: notepad
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5431:5432

    steps:
      - uses: actions/checkout@v2

      # - name: Build backend in Docker
      #   run: |
      #     docker-compose pull
      #     docker-compose up -Vd db
      #     docker_host_ip=$(ip route show | awk '/default/ {print $3}') docker-compose build backend
      #     docker-compose up backend
      #     docker-compose down -v

      - name: Build backend in Docker
        run: |
          # docker-compose pull
          # docker-compose up -Vd db
          # bash -c "export PGPASSWORD=admin; psql -h db -p 5431 -U admin -d notepad -f init.sql
          bash -c "export PGPASSWORD=admin; psql -h db -p 5432 -U admin -d notepad -c \"SELECT version();\" > output.txt"
          echo $(cat output.txt)
          # docker-compose down -v